name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    # Only run for non-prerelease releases
    if: ${{ !github.event.release.prerelease }}

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install uv and Python 3.10
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.10"

      - name: Build Package
        run: uv build

      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_PASSWORD }}
        run: uv publish
